version: '3'
services:
  bot:
    build: .
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      POSTGRES_DB: TGBL-API
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:
  postgres_backup:
